"""add wholesale price tiers

Revision ID: 4a807bde559d
Revises: 
Create Date: 2026-06-19 21:50:28.124807
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4a807bde559d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('prix_vente_gros', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('articles', sa.Column('prix_vente_super_gros', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'prix_vente_super_gros')
    op.drop_column('articles', 'prix_vente_gros')
    # ### end Alembic commands ###
