"""add prime_configs table

Revision ID: 9ab02411d259
Revises: 4a807bde559d
Create Date: 2026-06-19 22:04:01.905218
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9ab02411d259'
down_revision: str | None = '4a807bde559d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
